# Generated by Django 3.2.9 on 2021-12-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('event', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.member')),
                ('compensation', models.PositiveIntegerField()),
                ('position_name', models.CharField(max_length=200)),
            ],
            bases=('member.member',),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('difficulty', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.member')),
                ('join_date', models.DateField(max_length=200)),
            ],
            bases=('member.member',),
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(max_length=300)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.task')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('team_management', models.ManyToManyField(through='volunteer.Management', to='volunteer.Employee')),
                ('team_participation', models.ManyToManyField(through='volunteer.Participation', to='volunteer.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='volunteer_work',
            field=models.ManyToManyField(through='volunteer.WorksOn', to='volunteer.Volunteer'),
        ),
        migrations.AddField(
            model_name='participation',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.team'),
        ),
        migrations.AddField(
            model_name='participation',
            name='volunteer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer'),
        ),
        migrations.AddField(
            model_name='management',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.team'),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DateTimeField(blank=True, default='', null=True)),
                ('impressions', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='EventOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('entry_date', models.DateField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('organiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.employee')),
            ],
        ),
    ]
